version: '2.0'

services:
  
  redis:
    network_mode: host
    container_name: redis
    image: redis

  camera:
    image: cthorey/nest
    network_mode: host
    devices:
      - /dev/sensors/uwrist_camera:/dev/sensors/camera
    volumes:
      - /home/cthorey/workdir/nest:/workdir
    command: ./scripts/start_camera.sh
    restart: always

  ui:
    image: cthorey/nest
    network_mode: host
    volumes:
      - /home/cthorey/workdir/nest:/workdir
    command: streamlit run nest/app.py

  jupyter:
    image: cthorey/nest
    network_mode: host
    command: ./scripts/run_jupyter.sh
    volumes:
      - /home/cthorey/workdir/nest:/workdir
    



